### ISSUE TITLE
Cancel task after an error occurred?

### ISSUE THREAD

**Issue by h-evers** [arne-strout-icrossing/grunt-imagemagick#7]
Shouldn't the module stop the grunt process when an error occurs? Currently errors coming from the underlying imagemagick are just displayed as an info, but this can easily be overlooked in a longer grunt workflow. So in the "complete" callback function i would prefer a configurable flag where it is possible to stop on errors, i.e.

>  complete:function(err){
>     grunt.log.write('created '+this.props.dstPath+'--'+err+"\n");
>     if (err !== undefined && this.context.data.fatals === true) { grunt.warn(err); }
>     this.callback.apply(this.context,[this,true]);
>   }

**Comment by arne-strout-icrossing** [comment]
That should probably be the case. I will try to get to this one when I can, but if anyone wants to put in a pull request, I would not complain :)

**Comment by arne-strout-icrossing** [comment]
If your pull request fixed this problem, I'll go ahead and close this issue?

**Comment by h-evers** [comment]
Works for me - perfect!
